secrets:
    sops:
        age_key: ENC[AES256_GCM,data:59OuaHnp2ro34DqfkKsf0KGxXzPZbi86RvFDaIT1wQdT/Zb+Y6TkLTTUT57afOA5FCstrrEhshErYjqu2piYubOAf4PjGkQDo0UH,iv:Ol0LIwXJySYWEFeSuVmA+DwXYvATkpFqzXkmA9SPYUU=,tag:NQvLjIOgz7JBXtBLREJY1A==,type:str]
        registry:
            hostname: ENC[AES256_GCM,data:YeCnBeM2btpR2XB0ojUQw2r7xpzQGp4eEA==,iv:MAXEhlQ1mEeHRtFEzfdA6yzZr7YClHcEht/PInRNxxs=,tag:QyJCNBB6mBh8Zi1h+G+2cg==,type:str]
            username: ENC[AES256_GCM,data:gycKnILeTJClbFGnqZwwCp09+qAGgpgL+w==,iv:pJxDpSyv0WV2YQM+Th9HG/JVXzf4m3rbwENNL+t1gXY=,tag:rkYbPojgykG2lc8pfXEcIA==,type:str]
            password: ENC[AES256_GCM,data:uaGY77h1B7yo+QxsIrM=,iv:EqVJDZdWeOUN7T+BwGsSu5VuMWdtJADFMqZTzWnCzQs=,tag:G7urUVWjJRYdQCwBdVnoMQ==,type:str]
        git:
            basic_auth:
                username: ENC[AES256_GCM,data:h34ezA66a2ZLpBY=,iv:x4CuPLShdKHzqIhm3NjXhSkI32HIa7gDo806E+NGy2o=,tag:s41KTVdDQo8mhRc9dfjOTA==,type:str]
                password: ENC[AES256_GCM,data:/BQtnsOWrrNDY6Rh9AxXkd3b9ZIQ/T8znQ7VdO87ruRLBaswwO0iBA==,iv:wHHiETlwg45ypQZkumN15buISzEN9RgUBmg0Vt/0xfY=,tag:AF2td8CPHj4zfSkK8Mc/wQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age140kfw9jqh7d63svrgf8rpjaf8mteg507va4s98pnjtl975qe6stqfpaxvv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2ZFlVZGk4WkRZdVpYZnVu
            dmErdE1wQU5FRWhudTUxVUxScmRlOC9MWFY0CkN5Z1BMNXNiZnZtYkV0RFBGN2V1
            VFFjQ04rWVFGRDBjTUdYZlhMeWVaelkKLS0tIERJZDdmeHMyV1h4clF1aXhGWkty
            R2wzWnRUNlEvb1RTVTc4N1dkbFlKUzgKyZqIWPJ3Oo3LpK2b+jps3LLQ+nv9dBa4
            ZwCZDiOsGuxNEhACBaNe6VrKpiw/sMfDWdK2bPa732Pq2hWrLVe/hw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-02T14:10:23Z"
    mac: ENC[AES256_GCM,data:8BwBza6NNdR//ee0csPmLkb1Vbd4de59ElG6GDtekWZcH1s7f+jhn6xI+iwlp4Uq8117i2PKCTCZBW1u2YzssR6b3vSTZ4PG0uadQZTsIytLGf7tHIo7BNE9SDjZxXEFm4VUMz5PFis7YywWzMgcO5Mh66+Atnupq0Gtd80Kof8=,iv:kvuxsJ2fuPNtCPi7VDaTkPxNWtLJUnDTpy2rA5WoTXQ=,tag:GlGr027rMO3nl1jcz8Dz2A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
